/**
 * user.service.ts - User management business logic.
 *
 * Responsibilities:
 *   - List users (tenant + role scoped)
 *   - Get a user by id (scoped)
 *   - Create a user (temporary password generated and returned once)
 *   - Update user (name, phone)
 *   - Change status (activate / suspend)
 *   - Change role
 *
 * Enforces:
 *   - Tenant isolation via scope helpers
 *   - Role-based permission on which roles can be assigned
 *   - Email uniqueness
 *   - Super admin is never auto-created from the API
 */

import bcrypt from 'bcryptjs';
import { randomBytes } from 'node:crypto';
import { prisma } from '../../config/prisma.js';
import { logger } from '../../config/logger.js';
import {
    BadRequestError,
    ConflictError,
    ForbiddenError,
    NotFoundError,
} from '../../shared/errors/AppError.js';
import {
    buildTenantScope,
    assertCanAccessPartner,
    type ScopeUser,
} from '../../shared/utils/scope.js';
import { AuditAction, logAction } from '../../shared/utils/audit.js';
import type {
    ChangeRoleInput,
    ChangeStatusInput,
    CreateUserInput,
    ListUsersQuery,
    UpdateUserInput,
} from './user.schema.js';
import { RoleName, UserStatus } from '@prisma/client';

// --------------------------------------------------
// Public shape (never include passwordHash)
// --------------------------------------------------

export interface SafeUser {
    id: string;
    name: string;
    email: string;
    phone: string | null;
    role: string;
    partnerId: string | null;
    status: string;
    lastLoginAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
}

export interface CreateUserResult {
    user: SafeUser;
    /**
     * The temporary password generated by the service.
     * Only returned once at creation time. Never persisted in plaintext.
     * Caller must convey it to the user out of band.
     */
    temporaryPassword: string;
}

// --------------------------------------------------
// Helpers
// --------------------------------------------------

const TEMP_PASSWORD_BYTES = 12;

const generateTemporaryPassword = (): string => {
    // 12 bytes → base64 → ~16 chars. Always contains mixed case + digits
    // because base64 uses A–Z, a–z, 0–9, plus + and /.
    return randomBytes(TEMP_PASSWORD_BYTES).toString('base64url').slice(0, 16);
};

const toSafeUser = (user: {
    id: string;
    name: string;
    email: string;
    phone: string | null;
    partnerId: string | null;
    status: UserStatus;
    lastLoginAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    role: { name: RoleName };
}): SafeUser => ({
    id: user.id,
    name: user.name,
    email: user.email,
    phone: user.phone,
    role: user.role.name,
    partnerId: user.partnerId,
    status: user.status,
    lastLoginAt: user.lastLoginAt,
    createdAt: user.createdAt,
    updatedAt: user.updatedAt,
});

// --------------------------------------------------
// Permission rules for creating / assigning roles
// --------------------------------------------------

const assertCanAssignRole = (
    actor: ScopeUser,
    targetRole: RoleName,
): void => {
    // Nobody can create a SUPER_ADMIN via the API
    if (targetRole === RoleName.SUPER_ADMIN) {
        throw ForbiddenError('Cannot create or assign SUPER_ADMIN via the API');
    }

    // Only super_admin can create partner_admin
    if (targetRole === RoleName.PARTNER_ADMIN && actor.role !== 'SUPER_ADMIN') {
        throw ForbiddenError('Only SUPER_ADMIN can manage PARTNER_ADMIN users');
    }
};

// --------------------------------------------------
// List
// --------------------------------------------------

export interface ListUsersResult {
    data: SafeUser[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
}

export const listUsers = async (
    actor: ScopeUser,
    query: ListUsersQuery,
): Promise<ListUsersResult> => {
    const scope = buildTenantScope(actor);

    // Add query filters on top of the scope
    const where: Record<string, unknown> = { ...scope };

    if (query.role) where.role = { name: query.role };
    if (query.status) where.status = query.status;

    // Only super_admin may filter by an arbitrary partnerId
    if (query.partnerId) {
        if (actor.role !== 'SUPER_ADMIN') {
            throw ForbiddenError('Only SUPER_ADMIN can filter by partnerId');
        }
        where.partnerId = query.partnerId;
    }

    if (query.search) {
        where.OR = [
            { name: { contains: query.search, mode: 'insensitive' } },
            { email: { contains: query.search, mode: 'insensitive' } },
        ];
    }

    const skip = (query.page - 1) * query.limit;

    const [total, rows] = await prisma.$transaction([
        prisma.user.count({ where }),
        prisma.user.findMany({
            where,
            include: { role: true },
            orderBy: { createdAt: 'desc' },
            skip,
            take: query.limit,
        }),
    ]);

    const data = rows.map(toSafeUser);

    return {
        data,
        pagination: {
            page: query.page,
            limit: query.limit,
            total,
            totalPages: Math.ceil(total / query.limit),
        },
    };
};

// --------------------------------------------------
// Get by id
// --------------------------------------------------

export const getUserById = async (
    actor: ScopeUser,
    userId: string,
): Promise<SafeUser> => {
    const user = await prisma.user.findUnique({
        where: { id: userId },
        include: { role: true },
    });

    if (!user) throw NotFoundError('User not found');

    // Enforce scope
    if (actor.role !== 'SUPER_ADMIN') {
        if (!actor.partnerId || user.partnerId !== actor.partnerId) {
            throw ForbiddenError('Not allowed to access this user');
        }
    }

    return toSafeUser(user);
};

// --------------------------------------------------
// Create
// --------------------------------------------------

export const createUser = async (
    actor: ScopeUser,
    input: CreateUserInput,
): Promise<CreateUserResult> => {
    assertCanAssignRole(actor, input.role);

    // Determine target partnerId
    let targetPartnerId: string | null = null;

    if (actor.role === 'SUPER_ADMIN') {
        // super_admin can place a user in any partner (or none for internal)
        targetPartnerId = input.partnerId ?? null;
    } else {
        // partner_admin can only create users inside their own partner
        if (!actor.partnerId) {
            throw ForbiddenError('User is not associated with any partner');
        }
        targetPartnerId = actor.partnerId;

        // partner_admin cannot smuggle a different partnerId
        if (input.partnerId && input.partnerId !== actor.partnerId) {
            throw ForbiddenError('Not allowed to create users in another partner');
        }
    }

    // Roles other than SUPER_ADMIN must belong to a partner
    if (input.role !== RoleName.SUPER_ADMIN && !targetPartnerId) {
        throw BadRequestError(
            'Non-SUPER_ADMIN users must be assigned to a partner',
        );
    }

    // Email uniqueness
    const existing = await prisma.user.findUnique({
        where: { email: input.email },
        select: { id: true },
    });
    if (existing) {
        throw ConflictError('A user with this email already exists');
    }

    // Look up role id
    const roleRecord = await prisma.role.findUnique({
        where: { name: input.role },
        select: { id: true },
    });
    if (!roleRecord) {
        throw BadRequestError(`Role "${input.role}" not found`);
    }

    // Generate temporary password
    const temporaryPassword = generateTemporaryPassword();
    const passwordHash = await bcrypt.hash(temporaryPassword, 10);

    const created = await prisma.user.create({
        data: {
            name: input.name,
            email: input.email,
            phone: input.phone ?? null,
            partnerId: targetPartnerId,
            roleId: roleRecord.id,
            passwordHash,
            status: UserStatus.ACTIVE,
        },
        include: { role: true },
    });

    logger.info(
        { actorId: actor.id, userId: created.id, role: input.role },
        'user created',
    );

    void logAction({
        actorId: actor.id,
        partnerId: targetPartnerId,
        action: AuditAction.USER_CREATED,
        entityType: 'user',
        entityId: created.id,
        newValue: { email: created.email, role: input.role },
    });

    return {
        user: toSafeUser(created),
        temporaryPassword,
    };
};

// --------------------------------------------------
// Update (name, phone)
// --------------------------------------------------

export const updateUser = async (
    actor: ScopeUser,
    userId: string,
    input: UpdateUserInput,
): Promise<SafeUser> => {
    const existing = await prisma.user.findUnique({
        where: { id: userId },
        select: { id: true, partnerId: true },
    });

    if (!existing) throw NotFoundError('User not found');

    if (actor.role !== 'SUPER_ADMIN') {
        if (!actor.partnerId || existing.partnerId !== actor.partnerId) {
            throw ForbiddenError('Not allowed to update this user');
        }
    }

    const updated = await prisma.user.update({
        where: { id: userId },
        data: {
            name: input.name ?? undefined,
            phone: input.phone ?? undefined,
        },
        include: { role: true },
    });

    logger.info({ actorId: actor.id, userId }, 'user updated');

    return toSafeUser(updated);
};

// --------------------------------------------------
// Change status
// --------------------------------------------------

export const changeStatus = async (
    actor: ScopeUser,
    userId: string,
    input: ChangeStatusInput,
): Promise<SafeUser> => {
    // Only super_admin can change status for now
    if (actor.role !== 'SUPER_ADMIN') {
        throw ForbiddenError('Only SUPER_ADMIN can change user status');
    }

    if (actor.id === userId) {
        throw BadRequestError('You cannot change your own status');
    }

    const existing = await prisma.user.findUnique({
        where: { id: userId },
        select: { id: true },
    });
    if (!existing) throw NotFoundError('User not found');

    const updated = await prisma.user.update({
        where: { id: userId },
        data: { status: input.status },
        include: { role: true },
    });

    logger.info(
        { actorId: actor.id, userId, newStatus: input.status },
        'user status changed',
    );

    void logAction({
        actorId: actor.id,
        partnerId: updated.partnerId,
        action: AuditAction.USER_STATUS_CHANGED,
        entityType: 'user',
        entityId: userId,
        newValue: { status: input.status },
    });

    return toSafeUser(updated);
};

// --------------------------------------------------
// Change role
// --------------------------------------------------

export const changeRole = async (
    actor: ScopeUser,
    userId: string,
    input: ChangeRoleInput,
): Promise<SafeUser> => {
    if (actor.role !== 'SUPER_ADMIN') {
        throw ForbiddenError('Only SUPER_ADMIN can change user roles');
    }

    assertCanAssignRole(actor, input.role);

    if (actor.id === userId) {
        throw BadRequestError('You cannot change your own role');
    }

    const existing = await prisma.user.findUnique({
        where: { id: userId },
        select: { id: true, partnerId: true },
    });
    if (!existing) throw NotFoundError('User not found');

    // Non-super-admin roles must remain within a partner
    if (input.role !== RoleName.SUPER_ADMIN && !existing.partnerId) {
        throw BadRequestError(
            'Cannot assign a partner-scoped role to a user without a partner',
        );
    }

    const roleRecord = await prisma.role.findUnique({
        where: { name: input.role },
        select: { id: true },
    });
    if (!roleRecord) {
        throw BadRequestError(`Role "${input.role}" not found`);
    }

    const updated = await prisma.user.update({
        where: { id: userId },
        data: { roleId: roleRecord.id },
        include: { role: true },
    });

    logger.info(
        { actorId: actor.id, userId, newRole: input.role },
        'user role changed',
    );

    return toSafeUser(updated);
};

// Re-export the assertCanAccessPartner so callers can use it
export { assertCanAccessPartner };